"""
The Bestory Project
"""

MACHINE_ID = 0  # thru 1023

# Don't change next constants after you decide what values is

EPOCH = 1483228800000

TIMESTAMP_BITS = 41
MACHINE_ID_BITS = 10
SEQUENCE_NUMBER_BITS = 12

MAX_MACHINE_ID = -1 ^ (-1 << MACHINE_ID_BITS)

TIMESTAMP_SHIFT = MACHINE_ID_BITS + SEQUENCE_NUMBER_BITS
MACHINE_ID_SHIFT = SEQUENCE_NUMBER_BITS

MACHINE_ID_MASK = -1 ^ (-1 << MACHINE_ID_BITS) << MACHINE_ID_SHIFT
SEQUENCE_NUMBER_MASK = -1 ^ (-1 << SEQUENCE_NUMBER_BITS)
